apiVersion: 1

deleteDatasources:
  - name: ds_sql
    orgId: 1

datasources:
  - name: ds_sql
    type: mssql
    url: 'ms_sql:1433'
    database: fleet
    user: 'sa'
    jsonData:
      maxOpenConns: 0 # Grafana v5.4+
      maxIdleConns: 2 # Grafana v5.4+
      connMaxLifetime: 14400 # Grafana v5.4+
    secureJsonData:
      password: 'We@kP@ssword'