--- 
  rule_files:
    - "alerts.rules"
  alerting:
    alertmanagers:
    - static_configs:
      - targets:
        - alertmanager:9093
      scheme: http
      timeout: 10s
  global: 
    evaluation_interval: 15s
    scrape_interval: 15s
    scrape_timeout: 10s
  scrape_configs: 
    - job_name: prometheus
      static_configs: 
        - targets: 
            - "prometheus:9090"    
    - job_name: node_exporter
      metrics_path: /metrics
      scheme: http
      scrape_interval: 15s
      scrape_timeout: 10s
      static_configs: 
        - targets:
            - node_exporter:9100
          labels:
            environment: "dev"
            application: "etl"
            subapplication: "data processing"
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: target_address
        - source_labels: [__param_target]
          target_label: instance
          regex: '(?:[.?:]|https://|^)(.+?)(:[0-9]+)?'
          replacement: '${1}'
        - source_labels: [__address__]
          target_label: port
          regex: '(?:[.?:]|https://|^)(.+?):?([0-9]+)?'
          replacement: '${2}'